spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/resumeDb
    username: postgres
    password: postgres123
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092

  ai:
    openai:
      api-key: ${OPENAI_API_KEY:REQUIRED_FOR_OPENAI}
    google:
      genai:
        api-key: ${GEMINI_API_KEY:REQUIRED_FOR_GEMINI}

  ollama:
    cloud:
      base-url: ${OLLAMA_CHAT_URL:https://ollama.com}
      chat-model: ${OLLAMA_MODEL:minimax-m2.5:cloud}
