kafka.topic.analysis-job-topic: RESUME.AI.ANALYSIS_JOB_TOPIC
kafka.topic.skill-analysis-job-topic: SKILL.AI.ANALYSIS_JOB_TOPIC
spring:
  application:
    name: career-align-intelligence

  #redis configuration for caching and session management
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000
  # kafka configuration for both producer and consumer
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  # AI configuration for Ollama
  ai:
    ollama:
      base-url: https://ollama.com  # Or the specific cloud gateway provided by Ollama
      chat:
        options:
          #          model: qwen3-vl:235b-cloud
          #          model: nemotron-3-nano:30b-cloud
          #          model: gemma3:4b-cloud
          model: minimax-m2.5:cloud
    #          model: gemma3:12b-cloud

    #  DB configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/resumeDb
    username: postgres
    password: Srcem@123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: false
  sql:
    init:
      mode: never
  # flyway configuration for database migrations
  flyway:
    enabled: true
    locations: classpath:db/migration
    baselineOnMigrate: true
    baselineVersion: 0
#    validateOnMigrate: false
#    repairOnMigrate: true
# AI  Logging configuration for Ollama
logging:
  level:
    org.springframework.ai:
      chat.client: DEBUG
jwt:
  secret-key: as9b7aodlbjfkluosfd789ujeklfnlsduf90b8ha908w74tuqijvlckajdl
server:
  port: 8080
