spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      timeout: 60000
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}

  ai:
    openai:
      api-key: ${OPENROUTER_API_KEY}
    google:
      genai:
        api-key: ${GEMINI_API_KEY}

  ollama:
    cloud:
      base-url: ${OLLAMA_CHAT_URL}
      chat-model: ${OLLAMA_MODEL}
      api-key: ${OLLAMA_API_KEY}

logging:
  level:
    org.springframework.ai: INFO

jwt:
  secret-key: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRATION_MS}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

app:
  scraper-api-url: ${SCRAPER_API_URL}
  db:
    automation:
      container-name: ${DB_CONTAINER_NAME}
      backup-dir: ${DB_BACKUP_DIR}
      cron: ${DB_BACKUP_CRON}
